<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;
use App\Models\Reward;

class RewardApiTest extends TestCase
{
    /**
     * A basic feature test example.
     *
     * @return void
     */

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate:fresh');
    }


    public function test_example()
    {
        $rewards = Reward::factory(5)->create([
            'name'=> fake()->word() . 'laravel' . fake()->word()
        ]);
        $response = $this->get('/api/rewards/search?q=' . 'laravel');
        $response->assertStatus(200);
        dd($response->getContent());
        $this->assertEquals(5,collect(json_decode($response->getContent()))->count());
    }
}
