<?php

namespace Tests\Unit;

use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;
use App\Models\Reward;

class RewardTest extends TestCase
{
    /**
     * A basic unit test example.
     *
     * @return void
     */


    protected function setUp(): void
    {
        parent::setUp();
        Artisan::call('migrate');
    }

    protected function tearDown(): void
    {
        Artisan::call('migrate:reset');
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_that_default_reward_is_active()
    {
        $reward = Reward::factory()->make();
        $this->assertTrue($reward->is_active);
    }

    public function test_can_create_reward_in_db(){
        $reward = Reward::factory(3)->create();
        $this->assertEquals(3,Reward::count());
    }
}
